-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 3.5
-- Mon Jun 08 15:23:19 2026

-- parameterized module component declaration
component Accumulator
    port (DataA: in  std_logic_vector(17 downto 0); 
        DataB: in  std_logic_vector(17 downto 0); Clock: in  std_logic; 
        Reset: in  std_logic; ClockEn: in  std_logic; 
        Result: out  std_logic_vector(17 downto 0));
end component;

-- parameterized module component instance
__ : Accumulator
    port map (DataA(17 downto 0)=>__, DataB(17 downto 0)=>__, Clock=>__, 
        Reset=>__, ClockEn=>__, Result(17 downto 0)=>__);
