-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 3.5
--C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n Accumulator -lang vhdl -synth synplify -bus_exp 7 -bb -arch xo2c00 -type add -width 18 -unsigned -output_reg -enable -pipeline 0 

-- Mon Jun 08 15:23:19 2026

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library MACHXO2;
use MACHXO2.components.all;
-- synopsys translate_on

entity Accumulator is
    port (
        DataA: in  std_logic_vector(17 downto 0); 
        DataB: in  std_logic_vector(17 downto 0); 
        Clock: in  std_logic; 
        Reset: in  std_logic; 
        ClockEn: in  std_logic; 
        Result: out  std_logic_vector(17 downto 0));
end Accumulator;

architecture Structure of Accumulator is

    -- internal signal declarations
    signal scuba_vhi: std_logic;
    signal r0_sum17: std_logic;
    signal r0_sum16: std_logic;
    signal r0_sum15: std_logic;
    signal r0_sum14: std_logic;
    signal r0_sum13: std_logic;
    signal r0_sum12: std_logic;
    signal r0_sum11: std_logic;
    signal r0_sum10: std_logic;
    signal r0_sum9: std_logic;
    signal r0_sum8: std_logic;
    signal r0_sum7: std_logic;
    signal r0_sum6: std_logic;
    signal r0_sum5: std_logic;
    signal r0_sum4: std_logic;
    signal r0_sum3: std_logic;
    signal r0_sum2: std_logic;
    signal r0_sum1: std_logic;
    signal r0_sum0: std_logic;
    signal tsum0: std_logic;
    signal tsum1: std_logic;
    signal tsum2: std_logic;
    signal co0: std_logic;
    signal tsum3: std_logic;
    signal tsum4: std_logic;
    signal co1: std_logic;
    signal tsum5: std_logic;
    signal tsum6: std_logic;
    signal co2: std_logic;
    signal tsum7: std_logic;
    signal tsum8: std_logic;
    signal co3: std_logic;
    signal tsum9: std_logic;
    signal tsum10: std_logic;
    signal co4: std_logic;
    signal tsum11: std_logic;
    signal tsum12: std_logic;
    signal co5: std_logic;
    signal tsum13: std_logic;
    signal tsum14: std_logic;
    signal co6: std_logic;
    signal tsum15: std_logic;
    signal tsum16: std_logic;
    signal co7: std_logic;
    signal tsum17: std_logic;
    signal co8: std_logic;
    signal scuba_vlo: std_logic;

    -- local component declarations
    component FADD2B
        port (A0: in  std_logic; A1: in  std_logic; B0: in  std_logic; 
            B1: in  std_logic; CI: in  std_logic; COUT: out  std_logic; 
            S0: out  std_logic; S1: out  std_logic);
    end component;
    component FD1P3DX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            CD: in  std_logic; Q: out  std_logic);
    end component;
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    attribute GSR : string; 
    attribute GSR of FF_17 : label is "ENABLED";
    attribute GSR of FF_16 : label is "ENABLED";
    attribute GSR of FF_15 : label is "ENABLED";
    attribute GSR of FF_14 : label is "ENABLED";
    attribute GSR of FF_13 : label is "ENABLED";
    attribute GSR of FF_12 : label is "ENABLED";
    attribute GSR of FF_11 : label is "ENABLED";
    attribute GSR of FF_10 : label is "ENABLED";
    attribute GSR of FF_9 : label is "ENABLED";
    attribute GSR of FF_8 : label is "ENABLED";
    attribute GSR of FF_7 : label is "ENABLED";
    attribute GSR of FF_6 : label is "ENABLED";
    attribute GSR of FF_5 : label is "ENABLED";
    attribute GSR of FF_4 : label is "ENABLED";
    attribute GSR of FF_3 : label is "ENABLED";
    attribute GSR of FF_2 : label is "ENABLED";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    FF_17: FD1P3DX
        port map (D=>tsum17, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum17);

    FF_16: FD1P3DX
        port map (D=>tsum16, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum16);

    FF_15: FD1P3DX
        port map (D=>tsum15, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum15);

    FF_14: FD1P3DX
        port map (D=>tsum14, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum14);

    FF_13: FD1P3DX
        port map (D=>tsum13, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum13);

    FF_12: FD1P3DX
        port map (D=>tsum12, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum12);

    FF_11: FD1P3DX
        port map (D=>tsum11, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum11);

    FF_10: FD1P3DX
        port map (D=>tsum10, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum10);

    FF_9: FD1P3DX
        port map (D=>tsum9, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum9);

    FF_8: FD1P3DX
        port map (D=>tsum8, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum8);

    FF_7: FD1P3DX
        port map (D=>tsum7, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum7);

    FF_6: FD1P3DX
        port map (D=>tsum6, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum6);

    FF_5: FD1P3DX
        port map (D=>tsum5, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum5);

    FF_4: FD1P3DX
        port map (D=>tsum4, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum4);

    FF_3: FD1P3DX
        port map (D=>tsum3, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum3);

    FF_2: FD1P3DX
        port map (D=>tsum2, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum2);

    FF_1: FD1P3DX
        port map (D=>tsum1, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum1);

    FF_0: FD1P3DX
        port map (D=>tsum0, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum0);

    addsub_0: FADD2B
        port map (A0=>scuba_vlo, A1=>DataA(0), B0=>scuba_vlo, 
            B1=>DataB(0), CI=>scuba_vlo, COUT=>co0, S0=>open, S1=>tsum0);

    addsub_1: FADD2B
        port map (A0=>DataA(1), A1=>DataA(2), B0=>DataB(1), B1=>DataB(2), 
            CI=>co0, COUT=>co1, S0=>tsum1, S1=>tsum2);

    addsub_2: FADD2B
        port map (A0=>DataA(3), A1=>DataA(4), B0=>DataB(3), B1=>DataB(4), 
            CI=>co1, COUT=>co2, S0=>tsum3, S1=>tsum4);

    addsub_3: FADD2B
        port map (A0=>DataA(5), A1=>DataA(6), B0=>DataB(5), B1=>DataB(6), 
            CI=>co2, COUT=>co3, S0=>tsum5, S1=>tsum6);

    addsub_4: FADD2B
        port map (A0=>DataA(7), A1=>DataA(8), B0=>DataB(7), B1=>DataB(8), 
            CI=>co3, COUT=>co4, S0=>tsum7, S1=>tsum8);

    addsub_5: FADD2B
        port map (A0=>DataA(9), A1=>DataA(10), B0=>DataB(9), 
            B1=>DataB(10), CI=>co4, COUT=>co5, S0=>tsum9, S1=>tsum10);

    addsub_6: FADD2B
        port map (A0=>DataA(11), A1=>DataA(12), B0=>DataB(11), 
            B1=>DataB(12), CI=>co5, COUT=>co6, S0=>tsum11, S1=>tsum12);

    addsub_7: FADD2B
        port map (A0=>DataA(13), A1=>DataA(14), B0=>DataB(13), 
            B1=>DataB(14), CI=>co6, COUT=>co7, S0=>tsum13, S1=>tsum14);

    addsub_8: FADD2B
        port map (A0=>DataA(15), A1=>DataA(16), B0=>DataB(15), 
            B1=>DataB(16), CI=>co7, COUT=>co8, S0=>tsum15, S1=>tsum16);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    addsub_9: FADD2B
        port map (A0=>DataA(17), A1=>scuba_vlo, B0=>DataB(17), 
            B1=>scuba_vlo, CI=>co8, COUT=>open, S0=>tsum17, S1=>open);

    Result(17) <= r0_sum17;
    Result(16) <= r0_sum16;
    Result(15) <= r0_sum15;
    Result(14) <= r0_sum14;
    Result(13) <= r0_sum13;
    Result(12) <= r0_sum12;
    Result(11) <= r0_sum11;
    Result(10) <= r0_sum10;
    Result(9) <= r0_sum9;
    Result(8) <= r0_sum8;
    Result(7) <= r0_sum7;
    Result(6) <= r0_sum6;
    Result(5) <= r0_sum5;
    Result(4) <= r0_sum4;
    Result(3) <= r0_sum3;
    Result(2) <= r0_sum2;
    Result(1) <= r0_sum1;
    Result(0) <= r0_sum0;
end Structure;

-- synopsys translate_off
library MACHXO2;
configuration Structure_CON of Accumulator is
    for Structure
        for all:FADD2B use entity MACHXO2.FADD2B(V); end for;
        for all:FD1P3DX use entity MACHXO2.FD1P3DX(V); end for;
        for all:VHI use entity MACHXO2.VHI(V); end for;
        for all:VLO use entity MACHXO2.VLO(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
