-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 3.5
-- Fri Jul 03 17:59:54 2026

-- parameterized module component declaration
component SMADD
    port (DataA: in  std_logic_vector(17 downto 0); 
        DataB: in  std_logic_vector(17 downto 0); 
        Result: out  std_logic_vector(17 downto 0));
end component;

-- parameterized module component instance
__ : SMADD
    port map (DataA(17 downto 0)=>__, DataB(17 downto 0)=>__, Result(17 downto 0)=>__);
