-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 7.5
-- Fri Jul 03 09:05:24 2026

-- parameterized module component declaration
component SMRAM
    port (Clock: in  std_logic; ClockEn: in  std_logic; 
        Reset: in  std_logic; WE: in  std_logic; 
        Address: in  std_logic_vector(7 downto 0); 
        Data: in  std_logic_vector(17 downto 0); 
        Q: out  std_logic_vector(17 downto 0));
end component;

-- parameterized module component instance
__ : SMRAM
    port map (Clock=>__, ClockEn=>__, Reset=>__, WE=>__, Address(7 downto 0)=>__, 
        Data(17 downto 0)=>__, Q(17 downto 0)=>__);
