-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 6.5
-- Thu Jun 11 22:10:13 2026

-- parameterized module component declaration
component SPS_RAM
    port (WrAddress: in  std_logic_vector(8 downto 0); 
        RdAddress: in  std_logic_vector(8 downto 0); 
        Data: in  std_logic_vector(17 downto 0); WE: in  std_logic; 
        RdClock: in  std_logic; RdClockEn: in  std_logic; 
        Reset: in  std_logic; WrClock: in  std_logic; 
        WrClockEn: in  std_logic; Q: out  std_logic_vector(17 downto 0));
end component;

-- parameterized module component instance
__ : SPS_RAM
    port map (WrAddress(8 downto 0)=>__, RdAddress(8 downto 0)=>__, Data(17 downto 0)=>__, 
        WE=>__, RdClock=>__, RdClockEn=>__, Reset=>__, WrClock=>__, 
        WrClockEn=>__, Q(17 downto 0)=>__);
